version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: bluffword-backend

  frontend:
    build:
      context: ../../frontend
    ports:
      - "3000:80"
    container_name: bluffword-frontend
    depends_on:
      - backend




